name: Sync Posters

on:
  workflow_dispatch:
  schedule:
    - cron: "25 7 * * *"
    - cron: "25 12 * * *"
    - cron: "25 14 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install gdown
        run: pip install gdown

      - name: Download Google Drive folder
        run: |
          gdown --folder https://drive.google.com/drive/folders/1FiycHId4_fkkjCCHdEt1EN2pnu5dhItr -O posters

      - name: Commit posters
        run: |
          git config --global user.email "bot@dear.com"
          git config --global user.name "Poster Bot"
          git add posters
          git commit -m "Auto update posters" || echo "No changes"
          git push
